```{r results='asis', echo=FALSE}
cat(paste0("\n", "###", cam_names[i], "\n"))
```

```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
dat <- filter(Data, Study == study, Vendor != camera) 


if(str_detect(variable, "IRF")){
  dat <- filter(dat, Fluid_Type == "IRF")
  
  f <- paste0(variable, "~", str_remove(variable, "IRF_"))
  f_mixed <- paste0(variable, "~", str_remove(variable, "IRF_"), "+", "(1|Ticket_number)")
}


if(str_detect(variable, "SRF")){
  dat <- filter(dat, Fluid_Type == "SRF")
  
  f <- paste0(variable, "~", str_remove(variable, "SRF_"))
  f_mixed <- paste0(variable, "~", str_remove(variable, "SRF_"), "+", "(1|Ticket_number)")
}

#dat$Visit <- factor(dat$Visit, levels = c("BSL", paste("Week", seq(4, 16, by = 4)), "Week  20", 
#                                          paste("Week", seq(24, 52, by = 4))))
#dat <- dat %>% 
#  group_by(Ticket_number) %>% 
#  filter(rank(Visit) == min(rank(Visit))) %>% 
#  ungroup()
```



```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
if(n_distinct(select(dat, variable)) == 1){
  cat("Kann kein Modell rechnen, da nur ein Level an Anwesenheit von Flüssigkeit")
} else {
  mod <- glm(f, family = "binomial", data = dat)
  pred <- predict(mod, type = "response")
  real <- unlist(select(dat, variable))
  
  roc_mod <- roc(real, pred)
  
  kable(table(select(dat, variable)),
        col.names = c(variable, "Frequency"),
        linesep = "",
        booktabs = T) %>% 
    kable_styling()
  
  ggroc(roc_mod) +
    labs(x = "Specificity", y = "Sensitivity") +
    theme_bw() +
    scale_y_continuous(expand = c(0.01, 0.01)) +
    scale_x_reverse(expand = c(0.01, 0.01))
}
```


```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
Sample_auc <- function(dat){
  dat <- dat %>% 
    group_by(Ticket_number) %>% 
    slice_sample(n = 1) %>% 
    ungroup()
  
  if(n_distinct(select(dat, variable)) != 1){
    mod <- glm(f, family = "binomial", data = dat)
    pred <- predict(mod, type = "response")
    real <- unlist(select(dat, variable))
    
    roc_mod <- roc(real, pred)
    
    return(auc(roc_mod))
  }
}

if(n_distinct(select(dat, variable)) != 1){
  cat(paste0("Area under the curve = ", sprintf("%.3f", round(auc(roc_mod), 3))))
}

if(study %in% c("TREND", "Protocol T")){
  aucs <- replicate(1000, Sample_auc(dat = dat))
  
  cat(paste0("\n", "95% CI for AUC: [", sprintf("%.3f", round(quantile(aucs, .025), 3)), "; ",
             sprintf("%.3f", round(quantile(aucs, .975), 3)), "]"))
}
```


```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
if(n_distinct(select(dat, variable)) != 1){
  optcoords <- coords(roc_mod, "best", best.method = "youden",
                      ret=c("threshold", "accuracy", "specificity", "sensitivity"))
  p <- optcoords["threshold"]
  beta <- summary(mod)$coefficients[, "Estimate"]
  
  cutoff <- unname((log(p/(1-p)) - beta[1])/beta[2])
  cat(paste0("Optimal cutoff for ", variable, " = ", sprintf("%.4f", round(cutoff, 3))))
}
```


```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
if(n_distinct(select(dat, variable)) != 1){
  
  tab <- kable(as.data.frame(t(optcoords[2:4])),
        booktabs = T,
        linesep = "",
        align = rep("c", 3),
        digits = 3) %>% 
    kable_styling(latex_options = "hold_position")
  
  print(tab)
  
  cat("\n")
}
```

\clearpage

