---
title: "Software for Reproducible Research"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Repository for IMS-RETREAT 2022**

This folder contains examples and references for the creation of packages, interactive documents and web pages to facilitate reproducibility of analysis and distribution of materials among peers.

## General tricks and toolkit 

- **IMS-repository** of useful programming functions. Toolkit by Teresa Engelbrecht

## Package Development

- Vignette how to create an R package and toy example
- **IMS-example**: CohortPlat by Elias Meyer: https://github.com/el-meyer/CohortPlat

## R-markdown

- Vignette: How to create a markdown document, and where to find some templates
- **IMS-examples**:
  - Consulting Statistischen Ambulanz template
  - Re-analysis template by Jonas Brugger

## Github websites

- Vignette how to create a website and toy example
- **IMS-example**: NCC by Pavla Krotka: https://pavlakrotka.github.io/NCC/


## References 

- Package development with devtools cheatsheet: https://raw.githubusercontent.com/rstudio/cheatsheets/main/package-development.pdf
- Hadley's book on package development: https://r-pkgs.org/
- R-markdown: https://tysonbarrett.com/Rstats/chapter-9-reproducible-workflow-with-rmarkdown.html
- References for websites: Hadley's book on package development: https://r-pkgs.org/

